CREATE TABLE IF NOT EXISTS `#__hrz_mobileconfig` (
  `id` INT(4) NOT NULL AUTO_INCREMENT ,
  `wifis` JSON NULL DEFAULT NULL ,
  `email` JSON NULL DEFAULT NULL ,
  `carddav` JSON NULL DEFAULT NULL ,
  `caldav` JSON NULL DEFAULT NULL ,
  `vpn` JSON NULL DEFAULT NULL ,

  UNIQUE `id` (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
